rules:
  description-empty: # Description shouldn't be empty
    level: warning
  description-max-length:
    level: error
    length: 12
  subject-empty: # Subject line should exist
    level: error
  type-empty: # Type must not be empty
    level: error
