version: "3"

dotenv:
  - .env

vars:
  BINARY_NAME: server
  PKG: ./cmd/server/main.go
  MIGRATION_PATH: ./migrations

tasks:
  default:
    cmds:
      - echo 'No default task'

  setup:
    desc: Setup the project
    cmds:
      - go mod tidy
      - go mod tidy -modfile=go.tool.mod

  upgrade:
    desc: Upgrade dependencies or tools (use `task upgrade -- tool`)
    cmds:
      - |
        if [ "{{.CLI_ARGS}}" = "tool" ]; then
          go get -modfile=go.tool.mod tool
        else
          go tool -modfile=go.tool.mod go-mod-upgrade
        fi

  build:
    desc: Build the project
    cmds:
      - go build -o {{.BINARY_NAME}} {{.PKG}}

  build-release-linux:
    desc: Build the project for production
    cmds:
      - CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o {{.BINARY_NAME}} {{.PKG}}

  test:
    desc: Run tests
    cmds:
      - go test -v ./...

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f {{.BINARY_NAME}}
      - rm -rf ./tmp/

  lint:
    desc: Run linter
    cmds:
      - go tool -modfile=go.tool.mod golangci-lint run

  run:
    desc: Build and run the application
    deps: [build]
    ignore_error: true
    cmds:
      - ./{{.BINARY_NAME}}
      - task: clean

  debug:
    desc: Debug the application
    cmds:
      - go run {{.PKG}}

  sqlc:
    desc: Generate source code from SQL
    cmds:
      - go tool -modfile=go.tool.mod sqlc generate

  docker-up:
    desc: Run docker-compose in dev mode
    cmds:
      - docker-compose -f compose.dev.yml --env-file .env up

  docker-down:
    desc: Stop docker containers
    cmds:
      - docker-compose -f compose.dev.yml --env-file .env down

  migrate-force:*:
    vars:
      VERSION: "{{index .MATCH 0}}"
    cmds:
      - go run -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest -path {{.MIGRATION_PATH}}/ -database "{{.DB_URL}}" force {{.VERSION}}

  migrate-up:
    cmds:
      - go run -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest -path {{.MIGRATION_PATH}}/ -database "{{.DB_URL}}" --verbose up

  migrate-up:*:
    vars:
      NUM: "{{index .MATCH 0}}"
    cmds:
      - go run -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest -path {{.MIGRATION_PATH}}/ -database "{{.DB_URL}}" --verbose up {{.NUM}}

  migrate-down:
    cmds:
      - go run -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest -path {{.MIGRATION_PATH}}/ -database "{{.DB_URL}}" --verbose down

  migrate-down:*:
    vars:
      NUM: "{{index .MATCH 0}}"
    cmds:
      - go run -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest -path {{.MIGRATION_PATH}}/ -database "{{.DB_URL}}" --verbose down {{.NUM}}

  new-migration:*:
    vars:
      NAME: "{{index .MATCH 0}}"
    cmds:
      - go run -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest create -ext sql -dir {{.MIGRATION_PATH}} -seq {{.NAME}}
