FROM oven/bun:1

WORKDIR /usr/src/app

COPY package.json bun.lock ./

RUN bun install --frozen-lockfile

COPY . .

# Expose the development port
EXPOSE 3000

# The ENTRYPOINT starts the dev server with hot-reloading
ENTRYPOINT ["bun", "run", "start:dev"]
