// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: document.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countUserDocuments = `-- name: CountUserDocuments :one
SELECT COUNT(*)
FROM documents
WHERE user_id = $1
`

func (q *Queries) CountUserDocuments(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUserDocuments, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (
    original_name,
	save_path,
    status,
    user_id
) VALUES (
  $1, $2, $3, $4
) RETURNING id, original_name, save_path, status, user_id, created_at, updated_at
`

type CreateDocumentParams struct {
	OriginalName string    `json:"original_name"`
	SavePath     string    `json:"save_path"`
	Status       string    `json:"status"`
	UserID       uuid.UUID `json:"user_id"`
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.OriginalName,
		arg.SavePath,
		arg.Status,
		arg.UserID,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OriginalName,
		&i.SavePath,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM documents
WHERE id = $1 AND user_id = $2
`

type DeleteDocumentParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteDocument(ctx context.Context, arg DeleteDocumentParams) error {
	_, err := q.db.Exec(ctx, deleteDocument, arg.ID, arg.UserID)
	return err
}

const getDocument = `-- name: GetDocument :one
SELECT id, original_name, save_path, user_id, status, created_at, updated_at
FROM documents
WHERE id = $1 AND user_id = $2
LIMIT 1
`

type GetDocumentParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

type GetDocumentRow struct {
	ID           uuid.UUID `json:"id"`
	OriginalName string    `json:"original_name"`
	SavePath     string    `json:"save_path"`
	UserID       uuid.UUID `json:"user_id"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) (GetDocumentRow, error) {
	row := q.db.QueryRow(ctx, getDocument, arg.ID, arg.UserID)
	var i GetDocumentRow
	err := row.Scan(
		&i.ID,
		&i.OriginalName,
		&i.SavePath,
		&i.UserID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaginatedDocuments = `-- name: GetPaginatedDocuments :many
SELECT id, original_name, save_path, user_id, status, created_at, updated_at
FROM documents
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetPaginatedDocumentsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type GetPaginatedDocumentsRow struct {
	ID           uuid.UUID `json:"id"`
	OriginalName string    `json:"original_name"`
	SavePath     string    `json:"save_path"`
	UserID       uuid.UUID `json:"user_id"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) GetPaginatedDocuments(ctx context.Context, arg GetPaginatedDocumentsParams) ([]GetPaginatedDocumentsRow, error) {
	rows, err := q.db.Query(ctx, getPaginatedDocuments, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPaginatedDocumentsRow{}
	for rows.Next() {
		var i GetPaginatedDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.OriginalName,
			&i.SavePath,
			&i.UserID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentStatus = `-- name: UpdateDocumentStatus :one
UPDATE documents
SET status = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, original_name, save_path, status, user_id, created_at, updated_at
`

type UpdateDocumentStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateDocumentStatus(ctx context.Context, arg UpdateDocumentStatusParams) (Document, error) {
	row := q.db.QueryRow(ctx, updateDocumentStatus, arg.ID, arg.Status)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.OriginalName,
		&i.SavePath,
		&i.Status,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
