// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteRefreshTokenByUserID(ctx context.Context, userID uuid.UUID) error
	GetRefreshTokenHashByUserID(ctx context.Context, userID uuid.UUID) (GetRefreshTokenHashByUserIDRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error
	RevokeRefreshTokenByUserID(ctx context.Context, userID uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
