// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_token.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteRefreshTokenByUserID = `-- name: DeleteRefreshTokenByUserID :exec
DELETE FROM refresh_tokens
WHERE user_id = $1
`

func (q *Queries) DeleteRefreshTokenByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokenByUserID, userID)
	return err
}

const getRefreshTokenHashByUserID = `-- name: GetRefreshTokenHashByUserID :one
SELECT id, token_hash
FROM refresh_tokens
WHERE user_id = $1 AND revoked = false AND expires_at > NOW()
ORDER BY updated_at DESC
LIMIT 1
`

type GetRefreshTokenHashByUserIDRow struct {
	ID        uuid.UUID `json:"id"`
	TokenHash string    `json:"token_hash"`
}

func (q *Queries) GetRefreshTokenHashByUserID(ctx context.Context, userID uuid.UUID) (GetRefreshTokenHashByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenHashByUserID, userID)
	var i GetRefreshTokenHashByUserIDRow
	err := row.Scan(&i.ID, &i.TokenHash)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO refresh_tokens (
	user_id,
	token_hash,
	expires_at
) VALUES (
  $1, $2, $3
)
`

type InsertRefreshTokenParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const revokeRefreshTokenByUserID = `-- name: RevokeRefreshTokenByUserID :exec
UPDATE refresh_tokens
SET revoked = TRUE, revoked_at = NOW()
WHERE user_id = $1 AND revoked = false
`

func (q *Queries) RevokeRefreshTokenByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenByUserID, userID)
	return err
}
