[database]
url = "postgres://aidocument:password@localhost:5432/aidocument_dev"

[vector_database]
host = "vector_db"
port = 19530

[redis]
host = "redis"
port = 6379
password = "password"

[ai]
service_type = "gemini"
