[database]
url = "postgres://aidocument:password@db:5432/aidocument_prod"
max_connections = 20

[vector_database]
host = "vector_db"
port = 19530

[redis]
host = "redis"
port = 6379
password = "password"

[ai]
service_type = "gemini"
